export const BANNER_REQUEST = 'BANNER_REQUEST'
export const BANNER_SUCCESS = 'BANNER_SUCCESS'
export const BANNER_ERROR = 'BANNER_ERROR'

export const PROMOTE_REQUEST = 'PROMOTE_REQUEST'
export const PROMOTE_SUCCESS = 'PROMOTE_SUCCESS'
export const PROMOTE_ERROR = 'PROMOTE_ERROR'